name: Greetings

on: 
  workflow_dispatch:

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: version 1.0  # Set your desired tag name for the release
          release_name: Release v1.0  # Set your desired release name
          body: |
            test body
          draft: false
          prerelease: false
