name: Release

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
        version:
          # Friendly description to be shown in the UI instead of 'name'
          description: version
          # Default value if no value is explicitly provided
          default: '1.1.0'
          # Input has to be provided for the workflow to run
          required: true
          # The data type of the input
          type: string
jobs:
  create-release:
    runs-on: windows-latest
    steps:
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.md
          tag_name: v${{ inputs.version }} 
          # note you'll typically need to create a personal access token
          # with permissions to create releases in the other repo
          token: ${{ secrets.PAT_TOKEN }}.
          # token: ${{ secrets.GITHUB_TOKEN }}
